// EDBS Wireframes — generated by source/build-code.js (do not edit)
const WIREFRAMES = [
  {
    "screenId": "SCR-001",
    "stateId": "ST-01",
    "title": "Default",
    "elements": [
      {
        "type": "logo"
      },
      {
        "type": "subtitle",
        "text": "Sign in"
      },
      {
        "type": "label",
        "text": "Email"
      },
      {
        "type": "input",
        "placeholder": "you@company.com"
      },
      {
        "type": "label",
        "text": "Password"
      },
      {
        "type": "input",
        "placeholder": "••••••••"
      },
      {
        "type": "button",
        "text": "Sign in",
        "primary": true
      }
    ]
  },
  {
    "screenId": "SCR-001",
    "stateId": "ST-02",
    "title": "Loading",
    "elements": [
      {
        "type": "logo"
      },
      {
        "type": "subtitle",
        "text": "Sign in"
      },
      {
        "type": "label",
        "text": "Email"
      },
      {
        "type": "input",
        "placeholder": "jane@company.com"
      },
      {
        "type": "label",
        "text": "Password"
      },
      {
        "type": "input",
        "placeholder": "••••••••"
      },
      {
        "type": "button",
        "text": "Signing in…",
        "primary": true
      },
      {
        "type": "note",
        "text": "(fields disabled)"
      }
    ]
  },
  {
    "screenId": "SCR-001",
    "stateId": "ST-03",
    "title": "Invalid credentials",
    "elements": [
      {
        "type": "logo"
      },
      {
        "type": "alert",
        "text": "! Invalid email or password",
        "variant": "error"
      },
      {
        "type": "subtitle",
        "text": "Sign in"
      },
      {
        "type": "label",
        "text": "Email"
      },
      {
        "type": "input",
        "placeholder": "jane@company.com"
      },
      {
        "type": "label",
        "text": "Password"
      },
      {
        "type": "input",
        "placeholder": ""
      },
      {
        "type": "button",
        "text": "Sign in",
        "primary": true
      }
    ]
  },
  {
    "screenId": "SCR-001",
    "stateId": "ST-04",
    "title": "Deactivated account",
    "elements": [
      {
        "type": "logo"
      },
      {
        "type": "alert",
        "text": "! Account deactivated — contact administrator",
        "variant": "error"
      },
      {
        "type": "subtitle",
        "text": "Sign in"
      },
      {
        "type": "label",
        "text": "Email"
      },
      {
        "type": "input",
        "placeholder": "former@company.com"
      },
      {
        "type": "label",
        "text": "Password"
      },
      {
        "type": "input",
        "placeholder": ""
      },
      {
        "type": "button",
        "text": "Sign in",
        "primary": true
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-01",
    "title": "Default",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "datePicker",
        "label": "Book a desk for:"
      },
      {
        "type": "note",
        "text": "Select a date to view desk availability."
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-02",
    "title": "Loading",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "datePicker",
        "label": "Book a desk for:"
      },
      {
        "type": "skeletonGrid",
        "count": 4
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-03",
    "title": "Desks available",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ],
        "activeNav": "Book Desk"
      },
      {
        "type": "datePicker",
        "label": "Book a desk for:"
      },
      {
        "type": "table",
        "headers": [
          "Desk",
          "Status",
          "Action"
        ],
        "rows": [
          [
            "A-01",
            "● Available",
            "Book"
          ],
          [
            "A-02",
            "✗ Booked",
            "—"
          ],
          [
            "B-01",
            "● Available",
            "Book"
          ],
          [
            "B-02",
            "● Available",
            "Book"
          ]
        ]
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-04",
    "title": "Empty",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "empty",
        "text": "All desks booked for this date. Try another day."
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-05",
    "title": "Error",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "alert",
        "text": "! Could not load desks — Retry",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-06",
    "title": "Already booked",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "alert",
        "text": "ℹ You already have desk A-01. Cancel in My Bookings first.",
        "variant": "info"
      }
    ]
  },
  {
    "screenId": "SCR-002",
    "stateId": "ST-07",
    "title": "Confirm booking",
    "elements": [
      {
        "type": "modal",
        "title": "Confirm booking",
        "body": "Desk B-01 on Thu 14 Aug 2026",
        "actions": [
          "Cancel",
          "Confirm"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-003",
    "stateId": "ST-01",
    "title": "Default",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "subtitle",
        "text": "My bookings"
      },
      {
        "type": "table",
        "headers": [
          "Date",
          "Desk",
          "Status",
          "Action"
        ],
        "rows": [
          [
            "14 Aug 2026",
            "A-01",
            "● Confirmed",
            "Cancel"
          ],
          [
            "10 Aug 2026",
            "B-02",
            "○ Completed",
            "—"
          ]
        ]
      }
    ]
  },
  {
    "screenId": "SCR-003",
    "stateId": "ST-02",
    "title": "Loading",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "skeletonGrid",
        "count": 3
      }
    ]
  },
  {
    "screenId": "SCR-003",
    "stateId": "ST-03",
    "title": "Empty",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "empty",
        "text": "No bookings yet. → Book a desk"
      }
    ]
  },
  {
    "screenId": "SCR-003",
    "stateId": "ST-04",
    "title": "Error",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Book Desk",
          "My Bookings"
        ]
      },
      {
        "type": "alert",
        "text": "! Could not load bookings — Retry",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-003",
    "stateId": "ST-05",
    "title": "Cancel confirm",
    "elements": [
      {
        "type": "modal",
        "title": "Cancel booking?",
        "body": "Desk A-01 on 14 Aug 2026",
        "actions": [
          "Keep booking",
          "Confirm cancel"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-004",
    "stateId": "ST-01",
    "title": "Default",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "All Bookings",
        "admin": true
      },
      {
        "type": "filters",
        "labels": [
          "Date: All",
          "Status: All",
          "Apply"
        ]
      },
      {
        "type": "table",
        "headers": [
          "Date",
          "Employee",
          "Desk",
          "Status",
          "Action"
        ],
        "rows": [
          [
            "14 Aug 2026",
            "jane@co.com",
            "A-01",
            "● Confirmed",
            "Cancel"
          ],
          [
            "13 Aug 2026",
            "bob@co.com",
            "B-02",
            "● Confirmed",
            "Cancel"
          ]
        ]
      }
    ]
  },
  {
    "screenId": "SCR-004",
    "stateId": "ST-02",
    "title": "Loading",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "admin": true,
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "All Bookings"
      },
      {
        "type": "skeletonGrid",
        "count": 2
      }
    ]
  },
  {
    "screenId": "SCR-004",
    "stateId": "ST-03",
    "title": "Empty filter",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "admin": true,
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "All Bookings"
      },
      {
        "type": "empty",
        "text": "No bookings match filters. Clear filters"
      }
    ]
  },
  {
    "screenId": "SCR-004",
    "stateId": "ST-04",
    "title": "Error",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "admin": true,
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "All Bookings"
      },
      {
        "type": "alert",
        "text": "! Could not load bookings — Retry",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-004",
    "stateId": "ST-05",
    "title": "Filters applied",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "admin": true,
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "All Bookings"
      },
      {
        "type": "chips",
        "items": [
          "Date: 14 Aug 2026",
          "Status: Confirmed"
        ]
      },
      {
        "type": "table",
        "headers": [
          "Date",
          "Employee",
          "Desk",
          "Status",
          "Action"
        ],
        "rows": [
          [
            "14 Aug 2026",
            "jane@co.com",
            "A-01",
            "● Confirmed",
            "Cancel"
          ]
        ]
      }
    ]
  },
  {
    "screenId": "SCR-004",
    "stateId": "ST-06",
    "title": "Cancel on behalf",
    "elements": [
      {
        "type": "modal",
        "title": "Cancel for employee?",
        "body": "jane@co.com — A-01 on 14 Aug 2026",
        "actions": [
          "Keep booking",
          "Confirm cancel"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-01",
    "title": "Default",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Desks",
        "admin": true
      },
      {
        "type": "subtitle",
        "text": "Manage desks"
      },
      {
        "type": "button",
        "text": "+ Add desk",
        "primary": true,
        "width": 140
      },
      {
        "type": "table",
        "headers": [
          "Desk",
          "Status",
          "Actions"
        ],
        "rows": [
          [
            "A-12",
            "● Active",
            "Edit · Deactivate"
          ],
          [
            "B-03",
            "○ Inactive",
            "Edit · Activate"
          ]
        ]
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-02",
    "title": "Loading",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Desks",
        "admin": true
      },
      {
        "type": "skeletonGrid",
        "count": 3
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-03",
    "title": "Empty",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Desks",
        "admin": true
      },
      {
        "type": "empty",
        "text": "No desks yet. + Add desk"
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-04",
    "title": "Error",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Desks",
        "admin": true
      },
      {
        "type": "alert",
        "text": "! Could not load desks — Retry",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-05",
    "title": "Add desk",
    "elements": [
      {
        "type": "modal",
        "title": "Add desk",
        "body": "Desk number (e.g. A-12)",
        "actions": [
          "Cancel",
          "Save"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-06",
    "title": "Edit desk",
    "elements": [
      {
        "type": "modal",
        "title": "Edit desk",
        "body": "Desk number: A-12",
        "actions": [
          "Cancel",
          "Save"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-07",
    "title": "Deactivate confirm",
    "elements": [
      {
        "type": "modal",
        "title": "Deactivate desk?",
        "body": "Desk A-12 will not appear for booking.",
        "actions": [
          "Cancel",
          "Deactivate"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-005",
    "stateId": "ST-08",
    "title": "Deactivate blocked",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Desks",
        "admin": true
      },
      {
        "type": "alert",
        "text": "! B-03 has future bookings — cancel in All Bookings first",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-01",
    "title": "Default",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Users",
        "admin": true
      },
      {
        "type": "subtitle",
        "text": "Manage users"
      },
      {
        "type": "button",
        "text": "+ Add user",
        "primary": true,
        "width": 140
      },
      {
        "type": "table",
        "headers": [
          "Name",
          "Email",
          "Role",
          "Status",
          "Actions"
        ],
        "rows": [
          [
            "Jane Smith",
            "jane@co.com",
            "Employee",
            "● Active",
            "Edit · Reset · Deactivate"
          ],
          [
            "Marcus Lee",
            "admin@co.com",
            "Admin",
            "● Active",
            "Edit · Reset"
          ]
        ]
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-02",
    "title": "Loading",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Users",
        "admin": true
      },
      {
        "type": "skeletonGrid",
        "count": 3
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-03",
    "title": "Empty",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Users",
        "admin": true
      },
      {
        "type": "empty",
        "text": "No users found. + Add user"
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-04",
    "title": "Error",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Users",
        "admin": true
      },
      {
        "type": "alert",
        "text": "! Could not load users — Retry",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-05",
    "title": "Add user",
    "elements": [
      {
        "type": "modal",
        "title": "Add user",
        "body": "Name, email, role, initial password",
        "actions": [
          "Cancel",
          "Create"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-06",
    "title": "Edit user",
    "elements": [
      {
        "type": "modal",
        "title": "Edit user",
        "body": "Jane Smith — jane@co.com — Employee",
        "actions": [
          "Cancel",
          "Save"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-07",
    "title": "Reset password",
    "elements": [
      {
        "type": "modal",
        "title": "Password reset",
        "body": "New password (shown once): Kx9#mP2vLq — Copy now",
        "actions": [
          "Done"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-08",
    "title": "Deactivate confirm",
    "elements": [
      {
        "type": "modal",
        "title": "Deactivate user?",
        "body": "jane@co.com will not be able to sign in.",
        "actions": [
          "Cancel",
          "Deactivate"
        ]
      }
    ]
  },
  {
    "screenId": "SCR-006",
    "stateId": "ST-09",
    "title": "Last admin blocked",
    "elements": [
      {
        "type": "header",
        "title": "EDBS Admin",
        "nav": [
          "Desks",
          "Users",
          "All Bookings"
        ],
        "activeNav": "Users",
        "admin": true
      },
      {
        "type": "alert",
        "text": "! Cannot deactivate the last active Admin",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-007",
    "stateId": "ST-01",
    "title": "Default opt-out",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Desk Availability",
          "My Bookings"
        ],
        "activeNav": "My Bookings"
      },
      {
        "type": "subtitle",
        "text": "Notification settings"
      },
      {
        "type": "note",
        "text": "Email: confirmation, cancel, day-before reminder (automatic)"
      },
      {
        "type": "note",
        "text": "Browser push: Disabled"
      },
      {
        "type": "button",
        "text": "Enable push notifications",
        "primary": true,
        "width": 220
      },
      {
        "type": "note",
        "text": "← Back to my bookings"
      }
    ]
  },
  {
    "screenId": "SCR-007",
    "stateId": "ST-02",
    "title": "Push enabled",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Desk Availability",
          "My Bookings"
        ],
        "activeNav": "My Bookings"
      },
      {
        "type": "subtitle",
        "text": "Notification settings"
      },
      {
        "type": "note",
        "text": "Browser push: Enabled"
      },
      {
        "type": "button",
        "text": "Disable push notifications",
        "width": 220
      }
    ]
  },
  {
    "screenId": "SCR-007",
    "stateId": "ST-03",
    "title": "Browser unsupported",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Desk Availability",
          "My Bookings"
        ]
      },
      {
        "type": "alert",
        "text": "ℹ Browser push unavailable — email notifications still sent",
        "variant": "info"
      },
      {
        "type": "button",
        "text": "Enable push (disabled)",
        "width": 220
      }
    ]
  },
  {
    "screenId": "SCR-007",
    "stateId": "ST-04",
    "title": "Error saving",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Desk Availability",
          "My Bookings"
        ]
      },
      {
        "type": "alert",
        "text": "! Could not save preference — Retry",
        "variant": "error"
      }
    ]
  },
  {
    "screenId": "SCR-007",
    "stateId": "ST-05",
    "title": "Loading",
    "elements": [
      {
        "type": "header",
        "title": "EDBS",
        "nav": [
          "Desk Availability",
          "My Bookings"
        ]
      },
      {
        "type": "skeletonGrid",
        "count": 2
      }
    ]
  }
];

const FRAME_WIDTH = 1280;
const FRAME_HEIGHT = 800;
const COLUMNS = 3;
const GAP = 48;

function hex(h) {
  const n = h.replace('#', '');
  return {
    r: parseInt(n.slice(0, 2), 16) / 255,
    g: parseInt(n.slice(2, 4), 16) / 255,
    b: parseInt(n.slice(4, 6), 16) / 255,
  };
}

/** Grayscale — low-fidelity wireframes */
const WIRE_PALETTE = {
  bg: { r: 0.96, g: 0.96, b: 0.96 },
  surface: { r: 1, g: 1, b: 1 },
  border: { r: 0.75, g: 0.75, b: 0.75 },
  borderStrong: { r: 0.2, g: 0.2, b: 0.2 },
  text: { r: 0.1, g: 0.1, b: 0.1 },
  muted: { r: 0.45, g: 0.45, b: 0.45 },
  fillDark: { r: 0.15, g: 0.15, b: 0.15 },
  onDark: { r: 1, g: 1, b: 1 },
  alertBg: { r: 0.94, g: 0.94, b: 0.94 },
  skeleton: { r: 0.88, g: 0.88, b: 0.88 },
  overlay: { r: 0, g: 0, b: 0 },
  primary: { r: 0.15, g: 0.15, b: 0.15 },
  onPrimary: { r: 1, g: 1, b: 1 },
  success: { r: 0.45, g: 0.45, b: 0.45 },
  successBg: { r: 0.92, g: 0.92, b: 0.92 },
  error: { r: 0.1, g: 0.1, b: 0.1 },
  errorBg: { r: 0.94, g: 0.94, b: 0.94 },
  errorBorder: { r: 0.2, g: 0.2, b: 0.2 },
  warning: { r: 0.1, g: 0.1, b: 0.1 },
  warningBg: { r: 0.94, g: 0.94, b: 0.94 },
  unavailableBg: { r: 0.92, g: 0.92, b: 0.92 },
};

/** From inception/design/tokens.css — client hi-fi (navy + green) */
const HIFI_PALETTE = {
  bg: hex('#ffffff'),
  bgMuted: hex('#f0f2f5'),
  surface: hex('#ffffff'),
  border: hex('#e2e8f0'),
  borderStrong: hex('#cbd5e1'),
  text: hex('#0d1b2a'),
  muted: hex('#64748b'),
  fillDark: hex('#0d1b2a'),
  onDark: hex('#ffffff'),
  nav: hex('#0d1b2a'),
  navLight: hex('#1b2d45'),
  primary: hex('#00e676'),
  onPrimary: hex('#0d1b2a'),
  success: hex('#047857'),
  successBg: hex('#ecfdf5'),
  successBorder: hex('#a7f3d0'),
  error: hex('#ef4444'),
  errorBg: hex('#fef2f2'),
  errorBorder: hex('#fecaca'),
  warning: hex('#a16207'),
  warningBg: hex('#fef9c3'),
  unavailableBg: hex('#f1f5f9'),
  skeleton: hex('#e2e8f0'),
  overlay: { r: 0.051, g: 0.106, b: 0.165 },
  alertBg: hex('#fef2f2'),
};

function createGenerator(config) {
  const C = config.palette;
  const hifi = config.hifi;
  const nameTag = config.nameTag;
  let yCursor = 0;
  let padX = 32;
  let contentW = FRAME_WIDTH - 64;
  let layoutAuth = false;
  let logoImage = null;
  const PAD = 32;

  async function loadFonts() {
    await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
    await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
    await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
  }

  async function loadLogo() {
    if (!hifi || typeof LOGO_BASE64 === 'undefined') return;
    const binary = atob(LOGO_BASE64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    logoImage = figma.createImage(bytes);
  }

  function placeLogo(parent, x, y, height) {
    const aspect = typeof LOGO_ASPECT === 'number' ? LOGO_ASPECT : 4.93;
    const w = height * aspect;
    if (hifi && logoImage) {
      const rect = figma.createRectangle();
      rect.name = 'Logo';
      rect.x = x;
      rect.y = y;
      rect.resize(w, height);
      rect.fills = [{ type: 'IMAGE', scaleMode: 'FIT', imageHash: logoImage.hash }];
      parent.appendChild(rect);
      return w;
    }
    const rect = figma.createRectangle();
    rect.name = 'Logo';
    rect.x = x;
    rect.y = y;
    rect.resize(w, height);
    rect.fills = [solid(C.surface)];
    rect.strokes = [solid(C.border)];
    rect.strokeWeight = 1;
    rect.cornerRadius = 4;
    parent.appendChild(rect);
    const label = figma.createText();
    label.fontName = { family: 'Inter', style: 'Medium' };
    label.characters = 'Desk Booking';
    label.fontSize = 11;
    label.fills = [solid(C.muted)];
    label.x = x + 8;
    label.y = y + Math.max(4, (height - 14) / 2);
    parent.appendChild(label);
    return w;
  }

  function solid(color, opacity = 1) {
    return { type: 'SOLID', color, opacity };
  }

  function parentSize(parent) {
    return {
      w: 'width' in parent ? parent.width : FRAME_WIDTH,
      h: 'height' in parent ? parent.height : FRAME_HEIGHT,
    };
  }

  function addShadow(node) {
    if (!hifi) return;
    node.effects = [
      {
        type: 'DROP_SHADOW',
        color: { r: 0, g: 0, b: 0, a: 0.07 },
        offset: { x: 0, y: 4 },
        radius: 6,
        spread: 0,
        visible: true,
        blendMode: 'NORMAL',
      },
    ];
  }

  function createShell(parent, width, height, x, y) {
    const shell = figma.createFrame();
    shell.name = 'Shell';
    shell.x = x;
    shell.y = y;
    shell.resize(width, height);
    shell.fills = [solid(C.surface)];
    shell.strokes = [solid(C.border)];
    shell.strokeWeight = 1;
    shell.cornerRadius = 12;
    shell.clipsContent = true;
    addShadow(shell);
    parent.appendChild(shell);
    return shell;
  }

  function text(parent, content, size, weight = 'Regular', color = C.text, x = padX, width = contentW) {
    const node = figma.createText();
    node.fontName = { family: 'Inter', style: weight };
    node.characters = content;
    node.fontSize = size;
    node.fills = [solid(color)];
    node.x = x;
    node.y = yCursor;
    node.resize(width, 40);
    node.textAutoResize = 'HEIGHT';
    parent.appendChild(node);
    yCursor += node.height + 12;
    return node;
  }

  function box(parent, w, h, fill = C.surface, stroke = true, x = padX) {
    const rect = figma.createRectangle();
    rect.x = x;
    rect.y = yCursor;
    rect.resize(w, h);
    rect.fills = [solid(fill)];
    if (stroke) {
      rect.strokes = [solid(C.border)];
      rect.strokeWeight = 1;
    }
    rect.cornerRadius = hifi ? 8 : 6;
    parent.appendChild(rect);
    yCursor += h + 12;
    return rect;
  }

  function primaryButton(parent, label, width = 200) {
    const h = 40;
    const fill = hifi ? C.primary : C.fillDark;
    const fg = hifi ? C.onPrimary : C.onDark;
    const rect = box(parent, width, h, fill, !hifi);
    if (!hifi) {
      rect.strokes = [solid(C.fillDark)];
    }
    const labelNode = figma.createText();
    labelNode.fontName = { family: 'Inter', style: 'Medium' };
    labelNode.characters = label;
    labelNode.fontSize = 14;
    labelNode.fills = [solid(fg)];
    labelNode.x = rect.x + 16;
    labelNode.y = rect.y + 11;
    parent.appendChild(labelNode);
  }

  function pill(parent, x, y, label, bg, fg, border) {
    const pillW = Math.max(label.length * 6.5 + 16, 72);
    const pillH = 22;
    const rect = figma.createRectangle();
    rect.x = x;
    rect.y = y;
    rect.resize(pillW, pillH);
    rect.fills = [solid(bg)];
    rect.cornerRadius = pillH / 2;
    if (border) {
      rect.strokes = [solid(border)];
      rect.strokeWeight = 1;
    }
    parent.appendChild(rect);
    const t = figma.createText();
    t.fontName = { family: 'Inter', style: 'Medium' };
    t.characters = label;
    t.fontSize = 10;
    t.fills = [solid(fg)];
    t.x = x + 8;
    t.y = y + 5;
    parent.appendChild(t);
    return pillW;
  }

  function renderElement(parent, el) {
    switch (el.type) {
      case 'logo': {
        const logoH = hifi ? 56 : 32;
        const logoW = logoH * (typeof LOGO_ASPECT === 'number' ? LOGO_ASPECT : 4.93);
        const lx = hifi && layoutAuth ? padX + (contentW - logoW) / 2 : padX;
        placeLogo(parent, lx, yCursor, logoH);
        yCursor += logoH + (hifi ? 24 : 16);
        break;
      }
      case 'title': {
        const node = text(parent, el.text, hifi ? 20 : 22, 'Bold');
        if (hifi && layoutAuth) {
          node.textAlignHorizontal = 'CENTER';
          node.x = padX;
          node.resize(contentW, 40);
        }
        break;
      }
      case 'subtitle':
        text(parent, el.text, 16, 'Medium');
        break;
      case 'label':
        text(parent, el.text, 12, 'Medium', C.muted);
        yCursor -= 4;
        break;
      case 'input':
        box(parent, el.width ?? contentW, 40);
        if (el.placeholder) {
          const ph = figma.createText();
          ph.fontName = { family: 'Inter', style: 'Regular' };
          ph.characters = el.placeholder;
          ph.fontSize = 14;
          ph.fills = [solid(C.muted)];
          ph.x = padX + 12;
          ph.y = yCursor - 40 + 11;
          parent.appendChild(ph);
        }
        break;
      case 'button':
        if (el.primary) {
          primaryButton(parent, el.text, el.width ?? contentW);
        } else {
          box(parent, el.width ?? contentW, 40, C.surface, true);
          const t = figma.createText();
          t.fontName = { family: 'Inter', style: 'Medium' };
          t.characters = el.text;
          t.fontSize = 14;
          t.x = padX + 16;
          t.y = yCursor - 40 + 11;
          parent.appendChild(t);
        }
        break;
      case 'alert': {
        const isInfo = el.variant === 'info';
        const bg = hifi ? (isInfo ? C.warningBg : C.errorBg) : C.alertBg;
        const stroke = hifi ? (isInfo ? C.warning : C.errorBorder) : C.borderStrong;
        const fg = hifi ? (isInfo ? C.warning : C.error) : C.text;
        const alertBox = box(parent, contentW, 48, bg);
        alertBox.strokes = [solid(stroke)];
        alertBox.strokeWeight = 1;
        text(parent, el.text, 13, 'Regular', fg, padX + 8, contentW - 16);
        yCursor -= 12;
        break;
      }
      case 'header': {
        const { w: barW } = parentSize(parent);
        const bar = figma.createFrame();
        bar.name = 'Header';
        bar.x = 0;
        bar.y = 0;
        bar.resize(barW, hifi ? 68 : 56);
        bar.fills = [solid(hifi ? C.nav : C.surface)];
        bar.strokes = [solid(hifi ? C.nav : C.border)];
        bar.strokeWeight = 1;
        bar.strokeAlign = 'INSIDE';
        parent.appendChild(bar);
        const logoH = hifi ? 36 : 28;
        const logoY = hifi ? 16 : 14;
        const logoW = placeLogo(bar, padX, logoY, logoH);
        if (el.nav?.length) {
          let nx = padX + logoW + 24;
          el.nav.forEach((item, i) => {
            const isActive = el.activeNav ? item === el.activeNav : i === 0;
            const navItem = figma.createText();
            navItem.fontName = { family: 'Inter', style: isActive && hifi ? 'Bold' : isActive ? 'Medium' : 'Regular' };
            navItem.characters = item;
            navItem.fontSize = 13;
            if (hifi && isActive) {
              const pill = figma.createRectangle();
              pill.x = nx - 8;
              pill.y = 18;
              pill.resize(item.length * 7 + 16, 32);
              pill.fills = [solid(C.primary)];
              pill.cornerRadius = 8;
              bar.appendChild(pill);
              navItem.fills = [solid(C.onPrimary)];
            } else {
              navItem.fills = [solid(hifi ? C.onDark : isActive ? C.text : C.muted, hifi ? (isActive ? 1 : 0.75) : 1)];
            }
            navItem.x = nx;
            navItem.y = hifi ? 26 : 20;
            bar.appendChild(navItem);
            nx += item.length * 7 + 24;
          });
        }
        const signOut = figma.createText();
        signOut.fontName = { family: 'Inter', style: 'Medium' };
        signOut.characters = 'Sign out';
        signOut.fontSize = 12;
        signOut.fills = [solid(hifi ? C.onDark : C.text, hifi ? 0.6 : 1)];
        signOut.x = barW - padX - 60;
        signOut.y = hifi ? 26 : 20;
        bar.appendChild(signOut);
        yCursor = hifi ? 84 : 72;
        break;
      }
      case 'datePicker':
        text(parent, el.label, 13, 'Regular');
        box(parent, 280, 36);
        break;
      case 'deskGrid': {
        const cols = 4;
        const cardW = (contentW - 36) / cols;
        const startY = yCursor;
        el.desks.forEach((desk, i) => {
          const col = i % cols;
          const row = Math.floor(i / cols);
          const card = figma.createFrame();
          card.x = padX + col * (cardW + 12);
          card.y = startY + row * 118;
          card.resize(cardW, 104);
          card.fills = [solid(desk.available || !hifi ? C.surface : C.unavailableBg)];
          card.strokes = [solid(C.border)];
          card.strokeWeight = 1;
          card.cornerRadius = 8;
          parent.appendChild(card);
          const num = figma.createText();
          num.fontName = { family: 'Inter', style: 'Bold' };
          num.characters = desk.id;
          num.fontSize = 16;
          num.fills = [solid(C.text)];
          num.x = card.x + 12;
          num.y = card.y + 10;
          num.textAlignHorizontal = 'CENTER';
          num.resize(cardW - 24, 20);
          parent.appendChild(num);
          const badgeLabel = desk.available ? '✓ Available' : '✗ Booked';
          if (hifi) {
            const badgeW = pill(
              parent,
              card.x + (cardW - 80) / 2,
              card.y + 34,
              badgeLabel,
              desk.available ? C.successBg : C.unavailableBg,
              desk.available ? C.success : C.muted,
              desk.available ? C.successBorder : null,
            );
            void badgeW;
          } else {
            const badge = figma.createText();
            badge.fontName = { family: 'Inter', style: 'Regular' };
            badge.characters = badgeLabel;
            badge.fontSize = 11;
            badge.fills = [solid(C.muted)];
            badge.x = card.x + 12;
            badge.y = card.y + 36;
            parent.appendChild(badge);
          }
          if (desk.available) {
            const btn = figma.createRectangle();
            btn.x = card.x + 12;
            btn.y = card.y + 64;
            btn.resize(cardW - 24, 28);
            btn.fills = [solid(hifi ? C.primary : C.fillDark)];
            btn.cornerRadius = 6;
            parent.appendChild(btn);
            const bt = figma.createText();
            bt.fontName = { family: 'Inter', style: 'Medium' };
            bt.characters = 'Book';
            bt.fontSize = 12;
            bt.fills = [solid(hifi ? C.onPrimary : C.onDark)];
            bt.x = btn.x + (cardW - 24) / 2 - 14;
            bt.y = btn.y + 6;
            parent.appendChild(bt);
          }
        });
        yCursor = startY + Math.ceil(el.desks.length / cols) * 118 + 12;
        break;
      }
      case 'skeletonGrid':
        for (let i = 0; i < el.count; i++) {
          box(parent, contentW, 100, hifi ? C.unavailableBg : C.skeleton, false);
        }
        break;
      case 'empty': {
        const node = text(parent, el.text, 14, 'Regular', C.muted);
        if (hifi) {
          node.textAlignHorizontal = 'CENTER';
          node.x = padX;
          node.resize(contentW, 40);
        }
        break;
      }
      case 'table': {
        text(parent, '', 1);
        yCursor -= 12;
        const rowH = 32;
        el.headers.forEach((h, i) => {
          const cell = figma.createText();
          cell.fontName = { family: 'Inter', style: 'Medium' };
          cell.characters = h;
          cell.fontSize = 11;
          cell.fills = [solid(C.muted)];
          cell.x = padX + i * 140;
          cell.y = yCursor;
          parent.appendChild(cell);
        });
        yCursor += rowH;
        el.rows.forEach((row) => {
          row.forEach((cellText, i) => {
            if (hifi && (cellText === 'Confirmed' || cellText === 'Completed' || cellText === 'Cancelled')) {
              const statusBg =
                cellText === 'Confirmed' ? C.successBg : cellText === 'Completed' ? C.unavailableBg : C.errorBg;
              const statusFg =
                cellText === 'Confirmed' ? C.success : cellText === 'Completed' ? C.muted : C.error;
              const statusBorder =
                cellText === 'Confirmed' ? C.successBorder : cellText === 'Cancelled' ? C.errorBorder : null;
              pill(parent, padX + i * 140, yCursor, cellText, statusBg, statusFg, statusBorder);
              return;
            }
            const cell = figma.createText();
            cell.fontName = { family: 'Inter', style: 'Regular' };
            cell.characters = cellText;
            cell.fontSize = 12;
            cell.fills = [solid(cellText === 'Cancel' && hifi ? C.primary : C.text)];
            cell.x = padX + i * 140;
            cell.y = yCursor + (hifi && cellText === 'Cancel' ? 4 : 0);
            parent.appendChild(cell);
          });
          yCursor += rowH;
          box(parent, contentW, 1, C.border, false);
          yCursor -= 12;
        });
        break;
      }
      case 'filters':
        el.labels.forEach((lbl, i) => {
          const t = figma.createText();
          t.fontName = { family: 'Inter', style: 'Regular' };
          t.characters = lbl;
          t.fontSize = 12;
          t.fills = [solid(C.text)];
          t.x = padX + i * 160;
          t.y = yCursor;
          if (lbl === 'Apply') {
            const btn = figma.createRectangle();
            btn.x = padX + i * 160;
            btn.y = yCursor;
            btn.resize(72, 32);
            btn.fills = [solid(hifi ? C.primary : C.fillDark)];
            btn.cornerRadius = 6;
            parent.appendChild(btn);
            t.fills = [solid(hifi ? C.onPrimary : C.onDark)];
            t.y = yCursor + 8;
            t.x = padX + i * 160 + 16;
          }
          parent.appendChild(t);
        });
        yCursor += 44;
        break;
      case 'chips':
        el.items.forEach((item, i) => {
          const chip = box(parent, 140, 24, hifi ? C.successBg : C.bg, true, padX + i * 150);
          if (hifi) {
            chip.strokes = [solid(C.successBorder)];
          }
          const t = figma.createText();
          t.fontName = { family: 'Inter', style: 'Regular' };
          t.characters = item;
          t.fontSize = 10;
          t.fills = [solid(hifi ? C.success : C.text)];
          t.x = padX + i * 150 + 8;
          t.y = yCursor - 24 + 6;
          parent.appendChild(t);
        });
        break;
      case 'modal': {
        const { w: pw, h: ph } = parentSize(parent);
        const overlay = figma.createRectangle();
        overlay.x = 0;
        overlay.y = 0;
        overlay.resize(pw, ph);
        overlay.fills = [solid(C.overlay, hifi ? 0.4 : 0.35)];
        parent.appendChild(overlay);
        const modalW = 400;
        const modalH = 180;
        const modal = figma.createFrame();
        modal.x = (pw - modalW) / 2;
        modal.y = (ph - modalH) / 2;
        modal.resize(modalW, modalH);
        modal.fills = [solid(C.surface)];
        modal.cornerRadius = 12;
        modal.strokes = [solid(C.border)];
        modal.strokeWeight = 1;
        addShadow(modal);
        parent.appendChild(modal);
        const mt = figma.createText();
        mt.fontName = { family: 'Inter', style: 'Bold' };
        mt.characters = el.title;
        mt.fontSize = 16;
        mt.fills = [solid(C.text)];
        mt.x = modal.x + 24;
        mt.y = modal.y + 24;
        parent.appendChild(mt);
        const mb = figma.createText();
        mb.fontName = { family: 'Inter', style: 'Regular' };
        mb.characters = el.body;
        mb.fontSize = 13;
        mb.fills = [solid(C.text)];
        mb.x = modal.x + 24;
        mb.y = modal.y + 56;
        parent.appendChild(mb);
        el.actions.forEach((action, i) => {
          const isPrimary = i === el.actions.length - 1;
          const bw = 160;
          const bx = modal.x + 24 + i * (bw + 12);
          const by = modal.y + modalH - 52;
          const rect = figma.createRectangle();
          rect.x = bx;
          rect.y = by;
          rect.resize(bw, 36);
          rect.fills = [solid(isPrimary ? (hifi ? C.primary : C.fillDark) : C.surface)];
          rect.cornerRadius = 6;
          rect.strokes = [solid(isPrimary ? (hifi ? C.primary : C.fillDark) : C.border)];
          rect.strokeWeight = 1;
          parent.appendChild(rect);
          const bt = figma.createText();
          bt.fontName = { family: 'Inter', style: 'Medium' };
          bt.characters = action;
          bt.fontSize = 12;
          bt.fills = [solid(isPrimary ? (hifi ? C.onPrimary : C.onDark) : C.text)];
          bt.x = bx + 16;
          bt.y = by + 10;
          parent.appendChild(bt);
        });
        yCursor = ph;
        break;
      }
      case 'spacer':
        yCursor += el.height;
        break;
      case 'note':
        text(parent, el.text, 12, 'Regular', C.muted);
        break;
    }
  }

  function buildFrame(state) {
    padX = PAD;
    contentW = FRAME_WIDTH - PAD * 2;
    layoutAuth = false;
    yCursor = PAD;

    const frame = figma.createFrame();
    frame.name = `${state.screenId}/${state.stateId} — ${state.title}${nameTag}`;
    frame.resize(FRAME_WIDTH, FRAME_HEIGHT);
    frame.clipsContent = true;

    const badge = figma.createText();
    badge.fontName = { family: 'Inter', style: 'Regular' };
    badge.characters = hifi ? `${state.screenId} / ${state.stateId} · Design` : `${state.screenId} / ${state.stateId}`;
    badge.fontSize = 10;
    badge.fills = [solid(C.muted)];
    badge.x = FRAME_WIDTH - 160;
    badge.y = 8;
    frame.appendChild(badge);

    let contentParent = frame;
    const hasHeader = state.elements.some((e) => e.type === 'header');
    frame.fills = [solid(hifi ? (hasHeader ? C.bgMuted : C.nav) : C.bg)];

    if (hifi) {
      if (hasHeader) {
        const shellW = FRAME_WIDTH - PAD * 2;
        const shellH = FRAME_HEIGHT - PAD * 2;
        contentParent = createShell(frame, shellW, shellH, PAD, PAD);
        padX = 24;
        contentW = shellW - padX * 2;
        yCursor = 0;
      } else {
        layoutAuth = true;
        const cardW = 420;
        const cardH = 520;
        contentParent = createShell(
          frame,
          cardW,
          cardH,
          (FRAME_WIDTH - cardW) / 2,
          (FRAME_HEIGHT - cardH) / 2,
        );
        padX = 32;
        contentW = cardW - padX * 2;
        yCursor = 32;
      }
    }

    for (const el of state.elements) {
      renderElement(contentParent, el);
    }
    return frame;
  }

  function isWireframeNode(n) {
    return n.type === 'FRAME' && n.name.startsWith('SCR-') && !n.name.includes('(Design)');
  }

  function isDesignNode(n) {
    return n.type === 'FRAME' && n.name.includes('(Design)');
  }

  async function generate() {
    await loadFonts();
    await loadLogo();
    const page = figma.currentPage;

    if (hifi) {
      page.findAll(isDesignNode).forEach((n) => n.remove());
    } else {
      page.findAll(isWireframeNode).forEach((n) => n.remove());
    }

    let startX = 0;
    let startY = 0;

    if (hifi) {
      const wireframes = page.findAll(isWireframeNode);
      if (wireframes.length > 0) {
        let maxX = 0;
        let minY = Infinity;
        wireframes.forEach((f) => {
          maxX = Math.max(maxX, f.x + f.width);
          minY = Math.min(minY, f.y);
        });
        startX = maxX + GAP;
        startY = minY;
      } else {
        for (const child of page.children) {
          if (child.type === 'FRAME' || child.type === 'GROUP') {
            startY = Math.max(startY, child.y + child.height + GAP);
          }
        }
      }
    } else {
      for (const child of page.children) {
        if (child.type === 'FRAME' || child.type === 'GROUP') {
          const bottom = child.y + ('height' in child ? child.height : 0);
          startY = Math.max(startY, bottom + GAP);
        }
      }
    }

    const frames = [];
    for (const state of WIREFRAMES) {
      frames.push(buildFrame(state));
    }

    frames.forEach((frame, index) => {
      const col = index % COLUMNS;
      const row = Math.floor(index / COLUMNS);
      frame.x = startX + col * (FRAME_WIDTH + GAP);
      frame.y = startY + row * (FRAME_HEIGHT + GAP);
      page.appendChild(frame);
    });

    figma.viewport.scrollAndZoomIntoView(frames);
    return frames.length;
  }

  return { generate, buildFrame, loadFonts };
}

const wireframeApi = createGenerator({
  palette: WIRE_PALETTE,
  hifi: false,
  nameTag: '',
});

const hiFiApi = createGenerator({
  palette: HIFI_PALETTE,
  hifi: true,
  nameTag: ' (Design)',
});

const generateWireframes = wireframeApi.generate;
const generateHiFiDesigns = hiFiApi.generate;
const buildHiFiFrame = hiFiApi.buildFrame;
const loadHiFiFonts = hiFiApi.loadFonts;

figma.showUI(__html__, { width: 360, height: 300 });

figma.ui.onmessage = async (msg) => {
  if (msg.type === 'generate') {
    try {
      const count = await generateWireframes();
      figma.ui.postMessage({ type: 'done', count });
      figma.notify(`Created ${count} wireframe frames on "${figma.currentPage.name}"`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      figma.ui.postMessage({ type: 'error', message });
      figma.notify(`Error: ${message}`, { error: true });
    }
  }
  if (msg.type === 'cancel') {
    figma.closePlugin();
  }
};
