const fs = require('fs');
const path = require('path');
const { buildLogoConstants } = require(path.join(
  __dirname,
  '..',
  '..',
  'EDBS_Wireframes',
  'source',
  'logo-constants.js',
));
const { assertValidPluginBundle } = require(path.join(
  __dirname,
  '..',
  '..',
  'EDBS_Wireframes',
  'source',
  'verify-bundle.js',
));

const dir = __dirname;
const repoRoot = path.join(dir, '..', '..', '..');
const pluginRoot = path.join(dir, '..');
const figmaPluginDir = path.join(pluginRoot, 'plugin');
const shared = path.join(pluginRoot, '..', 'EDBS_Wireframes', 'source');

const data = fs.readFileSync(path.join(shared, 'wireframe-data.ts'), 'utf8');
const match = data.match(/export const WIREFRAMES[\s\S]*?=\s*(\[[\s\S]*?\n\]);/);
if (!match) throw new Error('Could not parse WIREFRAMES from EDBS_Wireframes/source');
// eslint-disable-next-line no-eval
const WIREFRAMES = eval(match[1]);

const parts = [
  '// EDBS Figma — hi-fi screens (generated by source/build-code.js — do not edit)',
  'const WIREFRAMES = ' + JSON.stringify(WIREFRAMES, null, 2) + ';',
  '',
  'const FRAME_WIDTH = 1280;',
  'const FRAME_HEIGHT = 800;',
  'const COLUMNS = 3;',
  'const GAP = 48;',
  '',
  buildLogoConstants(repoRoot),
  fs.readFileSync(path.join(shared, 'design-palettes.js'), 'utf8'),
  fs.readFileSync(path.join(shared, 'render-engine.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'generate-from-wireframes.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'plugin-entry.js'), 'utf8'),
];

const bundle = parts.join('\n');
assertValidPluginBundle(bundle, 'EDBS_Figma');

fs.mkdirSync(figmaPluginDir, { recursive: true });
fs.writeFileSync(path.join(figmaPluginDir, 'code.js'), bundle);

const ui = fs.readFileSync(path.join(pluginRoot, 'ui.html'), 'utf8');
fs.writeFileSync(path.join(figmaPluginDir, 'ui.html'), ui);

const manifest = {
  name: 'EDBS_Figma',
  id: 'edbs-figma-hifi-v4',
  api: '1.0.0',
  main: 'code.js',
  capabilities: [],
  enableProposedApi: false,
  documentAccess: 'dynamic-page',
  editorType: ['figma'],
  ui: 'ui.html',
  networkAccess: { allowedDomains: ['none'] },
};
fs.writeFileSync(
  path.join(figmaPluginDir, 'manifest.json'),
  JSON.stringify(manifest, null, 2) + '\n',
);

const sizeKb = Math.round(bundle.length / 1024);
console.log('Generated EDBS_Figma plugin (' + sizeKb + ' KB)');
console.log('  Import folder: ' + figmaPluginDir);
if (sizeKb < 10) process.exit(1);
