const fs = require('fs');
const path = require('path');
const { assertValidPluginBundle } = require('./verify-bundle.js');

const dir = __dirname;
const pluginRoot = path.join(dir, '..');
const figmaPluginDir = path.join(pluginRoot, 'plugin');

const data = fs.readFileSync(path.join(dir, 'wireframe-data.ts'), 'utf8');
const match = data.match(/export const WIREFRAMES[\s\S]*?=\s*(\[[\s\S]*?\n\]);/);
if (!match) throw new Error('Could not parse WIREFRAMES array');
// eslint-disable-next-line no-eval
const WIREFRAMES = eval(match[1]);

const parts = [
  '// EDBS Wireframes — generated by source/build-code.js (do not edit)',
  'const WIREFRAMES = ' + JSON.stringify(WIREFRAMES, null, 2) + ';',
  '',
  'const FRAME_WIDTH = 1280;',
  'const FRAME_HEIGHT = 800;',
  'const COLUMNS = 3;',
  'const GAP = 48;',
  '',
  fs.readFileSync(path.join(dir, 'design-palettes.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'render-engine.js'), 'utf8'),
  fs.readFileSync(path.join(dir, 'code-plugin-entry.js'), 'utf8'),
];

const bundle = parts.join('\n');
assertValidPluginBundle(bundle, 'EDBS Wireframes');

fs.mkdirSync(figmaPluginDir, { recursive: true });
fs.writeFileSync(path.join(figmaPluginDir, 'code.js'), bundle);
fs.copyFileSync(path.join(pluginRoot, 'ui.html'), path.join(figmaPluginDir, 'ui.html'));

const manifest = {
  name: 'EDBS Wireframes',
  id: 'edbs-wireframes-v4',
  api: '1.0.0',
  main: 'code.js',
  capabilities: [],
  enableProposedApi: false,
  documentAccess: 'dynamic-page',
  editorType: ['figma'],
  ui: 'ui.html',
  networkAccess: { allowedDomains: ['none'] },
};
fs.writeFileSync(
  path.join(figmaPluginDir, 'manifest.json'),
  JSON.stringify(manifest, null, 2) + '\n',
);

const sizeKb = Math.round(bundle.length / 1024);
console.log('Generated code.js (' + sizeKb + ' KB, ' + WIREFRAMES.length + ' screens)');
console.log('  Figma import folder: ' + figmaPluginDir);
if (sizeKb < 10) {
  console.error('ERROR: code.js too small — build may have failed');
  process.exit(1);
}
